// <auto-generated />
using System;
using ETCGatewayAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ETCGatewayAPI.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260831143559_firstmigrationinlocaldb")]
    partial class firstmigrationinlocaldb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Etc.Shared.Models.ApiToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("Expiry")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TBL_ApiTokens");
                });

            modelBuilder.Entity("Etc.Shared.Models.ApiUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TBL_ApiUsers");
                });

            modelBuilder.Entity("Etc.Shared.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FatherName")
                        .HasColumnType("text");

                    b.Property<string>("MotherName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Active");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("TBL_Customers");
                });

            modelBuilder.Entity("Etc.Shared.Models.DoTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime>("BankTxnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("BankTxnId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BatchProcessId")
                        .HasColumnType("text");

                    b.Property<DateTime>("ChannelTransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("OriginalBankTxnId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PartnerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PartnerTransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PartnerTxnId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefNo1")
                        .HasColumnType("text");

                    b.Property<string>("RefNo2")
                        .HasColumnType("text");

                    b.Property<string>("RefNo3")
                        .HasColumnType("text");

                    b.Property<string>("RefNo4")
                        .HasColumnType("text");

                    b.Property<string>("RefNo5")
                        .HasColumnType("text");

                    b.Property<string>("ResponseCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResponseMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SettlDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SettlStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceAccountNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceChannel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TranMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TranStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TransactionAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BankTxnId")
                        .IsUnique();

                    b.HasIndex("PartnerTxnId");

                    b.HasIndex("WalletId");

                    b.ToTable("TBL_DoTransactions");
                });

            modelBuilder.Entity("Etc.Shared.Models.RequestLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("ClientIp")
                        .HasColumnType("text");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("RequestHeaders")
                        .HasColumnType("text");

                    b.Property<string>("RequestMethod")
                        .HasColumnType("text");

                    b.Property<string>("RequestPath")
                        .HasColumnType("text");

                    b.Property<string>("RequestPayload")
                        .HasColumnType("text");

                    b.Property<string>("RequestQuery")
                        .HasColumnType("text");

                    b.Property<DateTime>("RequestTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ResponsePayload")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResponseTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("integer");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TBL_RequestLogs");
                });

            modelBuilder.Entity("Etc.Shared.Models.Settlement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime>("BankTxnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("BatchProcessId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CBSResponse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NetCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("NetSettlementAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("ParkingGL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProcessBrCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ProcessedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ReverseAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("ReverseCount")
                        .HasColumnType("integer");

                    b.Property<string>("SettleBrCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SettledAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SettledBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SettlementAccountNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SettlementOperation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BatchProcessId")
                        .IsUnique();

                    b.ToTable("TBL_Settlements");
                });

            modelBuilder.Entity("Etc.Shared.Models.TransactionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("AccountNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("BalanceAfter")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("BalanceBefore")
                        .HasColumnType("numeric");

                    b.Property<string>("PartnerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PartnerTxnId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RequestTimestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResponseCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResponseData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResponseMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResponseTimestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SblTxnId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TranMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("TransactionAmount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("TBL_TransactionLogs");
                });

            modelBuilder.Entity("Etc.Shared.Models.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BrtaClass")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChassisNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("RhdClass")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UnregisterDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("VehicleCC")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VehicleColour")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VehicleRegistrationNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.ToTable("TBL_Vehicles");
                });

            modelBuilder.Entity("Etc.Shared.Models.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<decimal>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0.00m);

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("SONALI BANK PLC");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("BDT");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("MobileNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Active");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("BANK");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("WalletNo")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character(13)")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("MobileNo")
                        .IsUnique();

                    b.HasIndex("WalletNo")
                        .IsUnique();

                    b.ToTable("TBL_Wallets");
                });

            modelBuilder.Entity("Etc.Shared.Models.DoTransaction", b =>
                {
                    b.HasOne("Etc.Shared.Models.Wallet", "Wallet")
                        .WithMany("DoTransactions")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("Etc.Shared.Models.Vehicle", b =>
                {
                    b.HasOne("Etc.Shared.Models.Wallet", "Wallet")
                        .WithMany("Vehicles")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("Etc.Shared.Models.Wallet", b =>
                {
                    b.HasOne("Etc.Shared.Models.Customer", "Customer")
                        .WithMany("Wallets")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Etc.Shared.Models.Customer", b =>
                {
                    b.Navigation("Wallets");
                });

            modelBuilder.Entity("Etc.Shared.Models.Wallet", b =>
                {
                    b.Navigation("DoTransactions");

                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
